name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Test
        run: go test -v ./...

      - name: Build Binary
        run: |
          mkdir -p dist
          go build -o dist/notify .

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: notify-binary
          path: dist/notify

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Build for Multiple Platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/notify-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/notify-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o dist/notify-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o dist/notify-darwin-arm64 .
          GOOS=windows GOARCH=amd64 go build -o dist/notify-windows-amd64.exe .
          cd dist && \
          tar -czvf notify-linux-amd64.tar.gz notify-linux-amd64 && \
          tar -czvf notify-linux-arm64.tar.gz notify-linux-arm64 && \
          tar -czvf notify-darwin-amd64.tar.gz notify-darwin-amd64 && \
          tar -czvf notify-darwin-arm64.tar.gz notify-darwin-arm64 && \
          zip notify-windows-amd64.zip notify-windows-amd64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/notify-linux-amd64.tar.gz
            dist/notify-linux-arm64.tar.gz
            dist/notify-darwin-amd64.tar.gz
            dist/notify-darwin-arm64.tar.gz
            dist/notify-windows-amd64.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME || 'yourusername' }}/notify
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            latest
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 