name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Run Tests
        run: go test -v ./...

      - name: Build Binary (local)
        run: |
          mkdir -p dist
          go build -o dist/notify .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: notify-binary
          path: dist/notify

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Build for Multiple Platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/notify-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/notify-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o dist/notify-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o dist/notify-darwin-arm64 .
          GOOS=windows GOARCH=amd64 go build -o dist/notify-windows-amd64.exe .
          cd dist && \
          tar -czf notify-linux-amd64.tar.gz notify-linux-amd64 && \
          tar -czf notify-linux-arm64.tar.gz notify-linux-arm64 && \
          tar -czf notify-darwin-amd64.tar.gz notify-darwin-amd64 && \
          tar -czf notify-darwin-arm64.tar.gz notify-darwin-arm64 && \
          zip notify-windows-amd64.zip notify-windows-amd64.exe

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/notify-linux-amd64.tar.gz
            dist/notify-linux-arm64.tar.gz
            dist/notify-darwin-amd64.tar.gz
            dist/notify-darwin-arm64.tar.gz
            dist/notify-windows-amd64.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
